### ISSUE TITLE
Unable to activate app

### ISSUE THREAD

**Issue by paaland** [maros/Zway-InfluxDbStats#4]
When I try to activate this app in z-wave-me (2.3.5) I only get a "something went wrong" message.
I've ran "create database zwave" in influx so the database exists. Influx is available and running (I use it for other applications as well).

Url: http://192.168.10.10
Port: 8086
Database: zwave
Tag: influxdb
Interval: 5

**Comment by maros** [comment]
Did you install and instantiante the BaseModule first? Please also include the z-way log when this error occurs

**Comment by paaland** [comment]
I tried again now after some days (and rebootes) and this time it worked. Don't know what has happened in the mean time, but i fixed it.
