### ISSUE TITLE
Update interval does does not stick

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [maros/Zway-InfluxDbStats#5]
In the GUI for the module, you get a field where you are given the information that you should really set an update interval (which makes sense for later processing) but whatever you set in that field it is never retained (and never set actually).

Therefore, I always get a measurement into my database only on updates, not every 5 minutes which I would like to have.

- [ ] State the Z-Wave>Me version. See Management > Info

 v2.3.8-rc5

- [ ] Make sure that you followed all installation instructions in the README. If installed via git ensure that the directory is NOT prefixed with 'ZWay-' and that the user running zway can access all files inside the directory.

N/A

- [ ] Include log messages generated while running the highest log level. Log level can be set via /opt/z-way-server/config.xml (highest level = 0, file location may be different). Be sure to include enough context: Not only the line showing the error, but also a couple of lines before and after. Log file is usually located at /var/log/z-way-server.log

> [2018-07-16 22:12:59.225] [D] [zway] SETDATA devices.84.instances.0.commandClasses.152.data.rNonceAckWait = **********
> [2018-07-16 22:12:59.225] [D] [zway] SETDATA devices.84.data.lastNonceGet = 36729911 (0x02307437)
> [2018-07-16 22:12:59.225] [I] [zway] Waiting for job reply: Nonce Get
> [2018-07-16 22:13:01.323] [D] [zway] Job 0x13: deleted from queue
> [2018-07-16 22:13:01.419] [W] [zway] Reply not received before timeout for job (Nonce Get)
> [2018-07-16 22:13:02.946] [I] [core] --- Stopping module InfluxDb Statistics Collector
> [2018-07-16 22:13:02.962] [I] [core] --- Starting module InfluxDb Statistics Collector
> [2018-07-16 22:13:03.233] [D] [zway] Job 0x3b: deleted from queue
> [2018-07-16 22:13:07.472] [D] [zway] RECEIVED: ( 01 0B 00 04 00 0E 03 40 03 01 D5 00 6A )
> [2018-07-16 22:13:07.473] [D] [zway] SENT ACK
> [2018-07-16 22:13:07.473] [D] [zway] SETDATA devices.14.data.lastReceived = 0 (0x00000000)
> [2018-07-16 22:13:07.473] [D] [zway] SETDATA devices.14.instances.0.commandClasses.64.data.mode = 1 (0x00000001)

- [ ] Append the configuration of the module. The configuration can be obtained by opening this URL in your browser http://#IP#:8083/ZAutomation/api/v1/instances/#INSTANCE-ID#

> {"data":{"instanceId":"0","moduleId":"InfluxDbStats","active":"true","title":"Logger för förbrukning och temperatur till NAS influxdb","params":{"port":8086,"tags":["",""],"server":"xx.xx.xx.xx","database":"z-way","username":"xxxxxx","password":"xxxxxxxxxx","excludeTags":[]},"id":12,"creationTime":1531725573,"category":"logging"},"code":200,"message":"200 OK","error":null}

**Comment by maros** [comment]
Afaict this is a bug with the z-wave config form handling. Unfortunately there is nothing I can do here. The current workaround is to delete the app instance and create a new one.
