### ISSUE TITLE
"Database Server URL" wrong description

### ISSUE THREAD

**Issue by fenst** [maros/Zway-InfluxDbStats#6]
InfluxDb Statistics Collector = v1.06
Z-Wave.me = v2.3.8-rc6-5-geef5c8d
InfluxDB = v1.7.1

Hi. It seems to be a mistake in description of "Database Server URL" field.
The only value, which worked for me was "http://192.168.1.120", but not "http://192.168.1.120:8086/write" as if was suggested by description.
As it took a lot of time for me to find the correct field, and also for others, so could you please update the description?

**Comment by maros** [comment]
Help text says "The final URL used for writing will be $URL:$PORT/write. You have to include the protocol (ie. https:// )" which indicates that the url will be automatically built from the "Database Server URL" and "Database Server Port". Do you have any suggestions on how to improve this message?
