### ISSUE TITLE
Does not write if value is 0

### ISSUE THREAD

**Issue by amund7** [maros/Zway-InfluxDbStats#7]
InfluxDbStats does not seem to write anything to the database if the value is 0. This causes lots of strange behaviour when graphing and displaying these data, such as heat pump reporting to pull thousands of watts, even if it's been off for days.

Is there a 'feature' to not write zeros? If so, I'd like the option to turn that off.

**Comment by maros** [comment]
There is no code that would prevent this plugin from sending values=0 (my setup also works fine with values = 0). It looks like a plotting issue, or configuration issue (Update interval needs to be set) to me
